spring.application.name=demo

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/focus_todo}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.mvc.format.enum-case-insensitive=true

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.flyway.locations=classpath:db/migration
spring.flyway.enabled=true
# Принудительно проверять миграции при старте
spring.flyway.check-location=true
# Логировать SQL-запросы Flyway
logging.level.org.flywaydb=DEBUG
logging.level.org.springframework.boot.autoconfigure.flyway=DEBUG
